### ISSUE TITLE
How to turn on Flashlight for video call?

### ISSUE THREAD

**Issue by ananth10** [sinch/android-video-calling#10]
Can anyone tell me how  to turn on flashlight for video call?

**Comment by slavasav** [comment]
Hi,
This is not supported currently.

**Comment by ananth10** [comment]
thanks @slavasav  .

**Comment by ananth10** [comment]
is it possible to access camera parameters from sinch sdk ? or anyway to access camera to turn on flash light?

**Comment by slavasav** [comment]
No, not possible at the moment.

**Comment by ananth10** [comment]
Okay . thank you @slavasav
