### ISSUE TITLE
Android Sinch Video Call can't switch camera and resume videocontroller

### ISSUE THREAD

**Issue by cubatertech** [sinch/android-video-calling#24]
Hi. how are you.
Please follow this link. I facing the same issue that already posted at Stackoverflow.
I use sinch-android-rtc-3.8.0-VIDEO-SNAPSHOT.jar. Please give me some tips for fixing this issue. Thanks

**Comment by slavasav** [comment]
Hi,
Please use the latest SDK version (3.9.14), these issues have already been adressed.
