### ISSUE TITLE
Record Video Call

### ISSUE THREAD

**Issue by mayank250004** [sinch/android-video-calling#9]
can we record video call using sinch ?

**Comment by slavasav** [comment]
Hi,
No, only audio recording is supported at the moment.

**Comment by AAPBD** [comment]
I really need the video call features for our next upcoming government app. Is there any chance the get the feature soon? If Since can't provide this feature, we have to choose a different service.

**Comment by francoist** [comment]
Unfortunately, video recording will not be available in the upcoming releases this year.
